#!/usr/bin/env python3
"""Generate an OpenMW Lua lookup for cells owned by the Starwind compatibility plugin."""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess


CELL_RE = re.compile(r"^Record: CELL ")
NAME_RE = re.compile(r"^  Name: (.*)$")
FLAGS_RE = re.compile(r"^  Flags: (.*)$")
COORDINATES_RE = re.compile(r"^  Coordinates:\s+\((-?\d+),(-?\d+)\)$")
END_HEADER_RE = re.compile(r"^  RefId counter:")


def esmtool_dump(esmtool: pathlib.Path, source: pathlib.Path) -> list[str]:
    result = subprocess.run(
        [str(esmtool), "-t", "CELL", "dump", str(source)],
        check=True,
        capture_output=True,
        text=True,
        errors="replace",
    )
    return result.stdout.splitlines()


def collect_cells(esmtool: pathlib.Path, source: pathlib.Path) -> tuple[set[str], set[tuple[int, int]]]:
    interiors: set[str] = set()
    exteriors: set[tuple[int, int]] = set()
    in_header = False
    name = ""
    is_interior = False
    coordinates: tuple[int, int] | None = None

    for line in esmtool_dump(esmtool, source):
        if CELL_RE.match(line):
            in_header = True
            name = ""
            is_interior = False
            coordinates = None
            continue
        if not in_header:
            continue

        match = NAME_RE.match(line)
        if match:
            name = match.group(1).strip()
            continue
        match = FLAGS_RE.match(line)
        if match:
            is_interior = "Interior" in match.group(1)
            continue
        match = COORDINATES_RE.match(line)
        if match:
            coordinates = (int(match.group(1)), int(match.group(2)))
            continue
        if END_HEADER_RE.match(line):
            in_header = False
            if is_interior and name:
                interiors.add(name.lower())
            elif not is_interior and coordinates is not None:
                exteriors.add(coordinates)

    return interiors, exteriors


def lua_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(source: pathlib.Path, interiors: set[str], exteriors: set[tuple[int, int]]) -> str:
    lines = [
        "-- Generated by scripts/generate_starwind_music_cells.py; do not edit by hand.",
        f"-- Cell records: {source.name}",
        "local M = {}",
        "",
        "M.interiors = {",
    ]
    for name in sorted(interiors):
        lines.append(f"    [{lua_quote(name)}] = true,")
    lines.extend(["}", "", "M.exteriors = {"])
    for x, y in sorted(exteriors):
        lines.append(f'    ["{x},{y}"] = true,')
    lines.extend(["}", "", "return M", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--esmtool", required=True, type=pathlib.Path)
    parser.add_argument("--cell-esm", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    interiors, exteriors = collect_cells(args.esmtool, args.cell_esm)
    if not interiors or not exteriors:
        raise SystemExit("Expected both interior and exterior Starwind cells.")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.cell_esm, interiors, exteriors), encoding="utf-8", newline="\n")
    print(f"Generated {args.output}: {len(interiors)} interiors, {len(exteriors)} exteriors")


if __name__ == "__main__":
    main()
